language: go
go:
  - 1.11.x

env:
  - GO111MODULE=on

install:
  - true

script:
  - make test

deploy:
- provider: script
  skip_cleanup: true
  script: make deploy
  on:
    repo: jacobtomlinson/krontab
    tags: true
    condition: $TRAVIS_OS_NAME = linux
